config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'page#homepage'
  get 'about', to: 'page#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user  # this line creates after creating add_user_id_to_article
     validates :title, presence: true, length: {minimum: 3, maximum: 50}
     validates :description, presence: true, length: {minimum: 10, maximum: 300}

     validates :user_id, presence:true # this line creates after creating add_user_id_to_article

end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles, dependent: :destroy # this line creates after creating add_user_id_to_article
    #dependent: :destory add this line in user-22
    before_save {self.email = email.downcase} # this line creates after creating add_user_id_to_article
	validates :username, presence: true, 
	uniqueness: { case_sensitive: false }, 
	length: {minimum: 3, maximum: 25}


    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence:true,
	uniqueness: {case_sensitive: false},
	length: {maximum: 100},
	format: { with: VALID_EMAIL_REGEX }

	has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery with: :exception

	helper_method :current_user, :logged_in?

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in?
			flash[:danger] = "you must be login to perform that action"
			redirect_to root_path
		end

	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 
before_action :set_article, only: [:edit, :update, :show, :destroy]
before_action :require_user, except: [:index, :show]           #user 20
before_action :require_same_user, only: [:edit, :update, :destroy]  #user 20

 def index
   @articles = Article.paginate(page: params[:page], per_page: 4)
 end

  def new
 	@article = Article.new
  end

  def edit
    #@article = Article.find(params[:id]) we are calling this line in prviate path by defining def except create

  end

  def create
    #render plain: params[:article].inspect
    
    @article = Article.new(article_params)
    #@article.user = User.first
    @article.user = current_user #user 20 from here
    if @article.save
         flash[:success] = "Article was sucessfully created"
          redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
   # @article = Article.find(params[:id])
    if @article.update(article_params)
         flash[:success] = "Article was sucessfully update"
          redirect_to article_path(@article)
    else
     render 'edit'
     end      
  end

  def show
   # @article = Article.find(params[:id]) 
  end

  def destroy
   # @article = Article.find(params[:id])
    @article.destroy
    flash[:danger] = "Article sucessfully Deleted"
    redirect_to articles_path
  end

  private
   def set_article
    @article = Article.find(params[:id])
   end

  def article_params
    params.require(:article).permit(:title, :description)
  end
   
   #user 20 from here
  def require_same_user                   
      # if current_user != @article.user
      if current_user != @article.user and !current_user.admin?  #user-20 for admin user
        flash[:danger] = "you can only edit or delete your own article"
        redirect_to root_path
       end
  end
  #user 20 here

end

app/controllers/page_controller.rb
class PageController < ApplicationController

   def homepage
   	redirect_to articles_path if logged_in?  #user-19 
   end

   def about
   end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
      	session[:user_id] = user.id
      	flash[:success] = "you have sucessfully logged in"
      	redirect_to user_path(user)

      else
      	flash.now[:danger] ="there was something wrong with your login information"
      	render 'new'
      end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "logged out sucessfully"
		redirect_to root_path

	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show] #after creating user 19
  before_action :require_same_user, only: [:edit, :update, :destroy]  #user 20 and user-22
  before_action :require_admin , only: [:destroy]  #user-22
    def index
    	@user = User.paginate(page: params[:page], per_page: 4)
    end

	def new
	 @user = User.new
	end

	def create
      @user = User.new(user_params)

      if @user.save
      	session[:user_id]= @user.id   #after application 
      	flash[:success] = "welcome to the Beta blog #{@user.username}"
      	#redirect_to articles_path  after application 
      	redirect_to user_path(@user)
      else
      	render 'new'
      end
	end

	def edit
		#@user = User.find(params[:id])  after creating user
	end
   

	def update
		#@user = User.find(params[:id])   after creating user
		if @user.update(user_params)
          flash[:success] = "your account updated sucessfully"
          redirect_to articles_path

		else
			render 'edit'
		end
	end

	def show 
	  # @user =User.find(params[:id])  after creating user
   @user_articles = @user.articles.paginate(page: params[:page], per_page: 3)
    end
      
      # add this destroy line of code in user-22
    def destroy
          @user = User.find(params[:id])
          @user.destroy
          flash[:danger] = "User and all articles created by user have been deleted"
          redirect_to users_path
    end


	private
	 def user_params
      params.require(:user).permit(:username, :email, :password)
	 end


	def set_user                        
		@user = User.find(params[:id])  
	end
 
 #user 20 from here
    def require_same_user
    	if current_user != @user and !current_user.admin?
    		flash[:danger] = "you can only edit or delete your own article"
             redirect_to root_path
         end
    end
    #user 20 here

    #user-22
    def require_admin
      if logged_in? and !current_user.admin?
        flash[:danger] = "only admin users can perform that action"
        redirect_to root_path
    end
    end
    #user-22
end

app/helpers/application_helper.rb
module ApplicationHelper

	def gravatar_for(user, options ={ size: 80})
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      size = options[:size]
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
      image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
         <%= truncate(article.description, length: 50) %>
           <div class= "article-meta-details">
            <small>
              Created by: <%= article.user.username if article.user %>,
              <!-- if article.user this line is temporary beacuse we have the data without user id-->
              <%=  time_ago_in_words(article.created_at) %> ago,
              Last Update: <%=  time_ago_in_words(article.updated_at) %> ago
            </small>
          </div>
        </div>
        
              <!--user-20 below line for admin user after creation -->
              <% if logged_in? && (current_user == article.user || current_user.admin?)  %>
              <div class="article-actions">
              <%= link_to 'Edit this article', edit_article_path(article), class: "btn btn-x btn-primary" %>
              <%= link_to 'Delete this article', article_path(article), method: :delete,
                                                 data: {confirm: "Are you sure?"},
                                                 class: "btn btn-x btn-danger" %>
              </div>  
          <% end %>    <!--user-19 -->
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>


<!--<h2>The following error prevented the article from getting created</h2>
				<ul>
				<% @article.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>

				<% end %>
				</ul> -->

<div class='row'>
 <div class='col-xs-12'>
	<%= form_for(@article, html: {class: "form-horizontal", role: "form"}) do |f| %>

	 <div class='form-group'>
	  <div class='control-label col-sm-2'>
		<%= f.label :title %>
	  </div>
	  <div class='col-sm-8'>
		<%= f.text_field :title, class: "form-control", placeholder: "Title fo article", autofocus: true %>
	  </div>
	</div>

	<div class='form-group'>
	  <div class='control-label col-sm-2'>
		<%= f.label :description %>
	</div>
	<div class='col-sm-8'>
	  <%= f.text_area :description, rows:10, class: "form-control", placeholder: "Description fo article", autofocus:true %>
	 </div>
	</div>
	  
	  <div class="form-gropup">
	  	<div class="col-sm-offset-2 col-sm-10">
	  	<%= f.submit class:'btn btn-primary btn-lg' %>
	  </div>
	</div>
	<% end %>

    <div class="col-xs-4 col-xs-offset-4">
	[ <%= link_to 'Cancle request and return to article listing', articles_path %> ]
    </div>
 </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all article</h1>

<div align="center">
	<%= will_paginate %>
</div>	

<%= render 'article', obj:@articles %>

<div align="center">
	<%= will_paginate %>
</div>	

app/views/articles/new.html.erb
<h1 align="center">Create an Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<!-- <h1>Showing selected article</h1> -->

<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
    <!-- this line of code for user creation start-->
	<ul class="listing">
			<div class="row center">
				<div class="col-md-4 col-md-offset-4">
					<li>Created by:</li>
					<li><%= link_to gravatar_for(@article.user), user_path(@article.user) %>
					</li>
					<li class = "article-title">
						<%= link_to @article.user.username, user_path(@article.user) %>
					</li>

					<li>
						<small>
						<%= pluralize(@article.user.articles.count,"articles") if @article.user.articles %>
					    </small>
					</li>
				</div>
			</div>
		</ul>
    <!-- end -->

<h4 class="center description"><strong>Description:</strong></h4>
<hr>
	<%= simple_format(@article.description) %>


<div class="article-actions">
	
	   <!--user-20 below line for admin user after creation -->
	   <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
               <%= link_to 'Edit this article', edit_article_path(@article), class: "btn btn-x btn-primary" %>
               <%= link_to 'Delete this article', article_path(@article), method: :delete,
                                           data: {confirm: "Are you sure?"},
                                           class: "btn btn-x btn-danger" %>
    <% end %>    <!--user-19 -->
<%= link_to 'View All Article', articles_path, class: "btn btn-x btn-success" %>
</div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyright &copy; <a href="https://www.udemy.com">The Complete Ruby on Rails Developer</a>
			by <a href="#">Akash Bagde</a>
		</small>
		<nav>
			<ul>
				<li><%= link_to "About", about_path %></li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
      	<a href="#" class="close" data-dismiss="alert">&#215</a>
      	<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %> 
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" id="logo" href="#">Beta blog</a> -->
      <%= link_to "Beta blog", root_path, class: "navbar-brand", id:"logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to 'Users', users_path %></li>
         <% if logged_in? %>  <!--user-19 -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <!-- <li><a href="#">Action</a></li> -->
                <li><%= link_to "New Article", new_article_path %></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
         <% end %>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <li><%= link_to 'Log out', logout_path, method: :delete %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit your profile', edit_user_path(current_user) %></li> <!--user-19 -->
                <li><%= link_to 'View your profile', user_path(current_user) %></li> <!--user-19 -->
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>
        <% else %>
              <li><%= link_to 'Log in', login_path %></li>
               <li><%= link_to 'Sign Up', signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BetaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/page/about.html.erb
<h1>this is About page...</h1>

<%= link_to 'Homepage', root_path%>

app/views/page/homepage.html.erb
<div class="center jumbotron">
     <h1>BETA BLOG</h1>
     <!-- <%= link_to 'Beta Blog', articles_path %> | <%= link_to 'About', about_path%> -->
     <%= link_to 'Sign Up now', signup_path, class: "btn btn-danger btn-lg  btn-xlarge" %> 
     <!--user-19 signup_path -->
 </div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>

  <div class="row">
  	<div class="col-xs-8 col-xs-offset-2">
  	  <div class="panel panel-danger">
  	  	<div class="panel-heading">
  	  	  <h2 class="panel-title">
  	  	  	<%= pluralize(obj.errors.count, "error") %>
  	  	  	prohibited this article from being saved:
  	  	  </h2>
  	  	  <div class="panel-body">
	  	  	  	<ul>
	              <% obj.errors.full_messages.each do |msg| %>
		             <li><%= msg %></li>

	                 <% end %>
	            </ul>
           </div>
        </div>
      </div>
    </div>
  </div>			    
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class='row'>
 <div class='col-xs-12'>
	<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

	 <div class='form-group'>
	  <div class='control-label col-sm-2'>
		<%= f.label :Username %>
	  </div>
	  <div class='col-sm-8'>
		<%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
	  </div>
	</div>

	<div class='form-group'>
	  <div class='control-label col-sm-2'>
		<%= f.label :email %>
	</div>
	<div class='col-sm-8'>
	  <%= f.email_field :email, class: "form-control", placeholder: "Enter Email", autofocus:true %>
	 </div>
	</div>

	<div class='form-group'>
	  <div class='control-label col-sm-2'>
		<%= f.label :password %>
	</div>
	<div class='col-sm-8'>
	  <%= f.password_field :password, class: "form-control", placeholder: "Enter Password", autofocus:true %>
	 </div>
	</div>
	  
	  <div class="form-gropup">
	  	<div class="col-sm-offset-2 col-sm-10">
	  	<%= f.submit(@user.new_record? ? "Sign Up" : "Update account", class:'btn btn-primary btn-lg') %>
	  </div>
	</div>
	<% end %>

    <div class="col-xs-4 col-xs-offset-4">
	[ <%= link_to 'Cancle request and return to article listing', articles_path %> ]
    </div>
 </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your Account</h1>

<%= render 'form' %>















<!--
<%= render 'shared/errors', obj: @user %>

<div class='row'>
 <div class='col-xs-12'>
	<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

	 <div class='form-group'>
	  <div class='control-label col-sm-2'>
		<%= f.label :Username %>
	  </div>
	  <div class='col-sm-8'>
		<%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
	  </div>
	</div>

	<div class='form-group'>
	  <div class='control-label col-sm-2'>
		<%= f.label :email %>
	</div>
	<div class='col-sm-8'>
	  <%= f.email_field :email, class: "form-control", placeholder: "Enter Email", autofocus:true %>
	 </div>
	</div>

	<div class='form-group'>
	  <div class='control-label col-sm-2'>
		<%= f.label :password %>
	</div>
	<div class='col-sm-8'>
	  <%= f.password_field :password, class: "form-control", placeholder: "Enter Password", autofocus:true %>
	 </div>
	</div>
	  
	  <div class="form-gropup">
	  	<div class="col-sm-offset-2 col-sm-10">
	  	<%= f.submit "update your account", class:'btn btn-primary btn-lg' %>
	  </div>
	</div>
	<% end %>

    <div class="col-xs-4 col-xs-offset-4">
	[ <%= link_to 'Cancle request and return to article listing', articles_path %> ]
    </div>
 </div>
</div>

-->

app/views/users/index.html.erb
<h1 align="center">All Beta Blogger</h1>

<div align="center">
	<%= will_paginate @user %>
	<% @user.each do |user| %>
		<ul class="listing">
			<div class="row">
				<div class="well col-md-4 col-md-offset-4">
					<li><%= link_to gravatar_for(user), user_path(user) %>
					</li>
					<li class = "article-title">
						<%= link_to user.username, user_path(user) %>
					</li>

					<li>
						<small>
						<%= pluralize(user.articles.count,"articles") if user.articles %>
					    </small>
					    <!--user-22-->
					    <% if logged_in? and current_user.admin? %>
					    <li> <%= link_to "Delete this user", user_path(user), method: :delete, 
					    data: { confirm: "Are you sure you want to delete the user and their article ?"} %>
					    </li>

					    <% end %>
					    <!--user-22-->
					</li>
				</div>
			</div>
		</ul>
	<% end %>
	<%= will_paginate @user %>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign up for Beat Blog</h1>

<%= render 'form' %>

























<!--<%= render 'shared/errors', obj: @user %>

<div class='row'>
 <div class='col-xs-12'>
	<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

	 <div class='form-group'>
	  <div class='control-label col-sm-2'>
		<%= f.label :Username %>
	  </div>
	  <div class='col-sm-8'>
		<%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
	  </div>
	</div>

	<div class='form-group'>
	  <div class='control-label col-sm-2'>
		<%= f.label :email %>
	</div>
	<div class='col-sm-8'>
	  <%= f.email_field :email, class: "form-control", placeholder: "Enter Email", autofocus:true %>
	 </div>
	</div>

	<div class='form-group'>
	  <div class='control-label col-sm-2'>
		<%= f.label :password %>
	</div>
	<div class='col-sm-8'>
	  <%= f.password_field :password, class: "form-control", placeholder: "Enter Password", autofocus:true %>
	 </div>
	</div>
	  
	  <div class="form-gropup">
	  	<div class="col-sm-offset-2 col-sm-10">
	  	<%= f.submit "Sign Up", class:'btn btn-primary btn-lg' %>
	  </div>
	</div>
	<% end %>

    <div class="col-xs-4 col-xs-offset-4">
	[ <%= link_to 'Cancle request and return to article listing', articles_path %> ]
    </div>
 </div>
</div>

-->

app/views/users/show.html.erb
<h1 align="center"> welcome to <%= @user.username %>'s page</h1>

<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
     <%= gravatar_for @user, size: 150 %>
	</div>

</div>

<h4 align="center"><%=@user.username %>'s articles</h4>

<div class="center">
	<%= will_paginate @user_articles %>
</div>

<%= render 'articles/article', obj:@user_articles %>

<div class="center">
	<%= will_paginate @user_articles %>
</div>